apiVersion: v1
kind: Service
metadata:
  name: rancher-lb
  namespace: cattle-system
  labels:
    app: rancher
spec:
  type: LoadBalancer
  selector:
    app: rancher
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
