---
- name: Uninstall K3s
  hosts: all
  gather_facts: true
  pre_tasks:
  
    - name: Ensure ~/.kube directory exists
      command: "mkdir -p ~/.kube"
      delegate_to: localhost
      become: false
      changed_when: true
      run_once: true

    - name: Ensure ~/.kube directory is empty
      shell: "rm -rf ~/.kube/*"
      delegate_to: localhost
      become: false
      changed_when: true
      run_once: true
  roles:
    - role: master-uninstall
      tags: [ master-uninstall ]
      when: var_master is defined  or var_primordial_master is defined

    - role: worker-uninstall
      tags: [ worker-uninstall ]
      when: var_worker is defined  

    - role: docker-kill
      tags: [ docker-kill ]

   